### ISSUE TITLE
Adding new file to the source folder does not trigger a sync

### ISSUE THREAD

**Issue by julianpinedayyz** [kayo5994/gulp-file-sync#1]
When a new file is added to the source folder, this doesn't get synced to the destination folder.  Works when you delete a file but not when one is added.  Any feedback?

**Comment by kayo5994** [comment]
Unfortunately, the bug you mentioned failed to reappear on my own computer. So I guess it's caused by the gulp module of WATCH rather than mine. 

For example, the code below may cause the bug you mentioned:
`watch(['./*.*'], function() {
    fileSync('src', 'dest', {recursive: false});
  });`

Try the code below instead:

`watch(['*.*'], function() {
    fileSync('src', 'dest', {recursive: false});
  });`
